Upgrade the checked-in version of Maven from 2.2.1 to 3.03

diff --git a/tools/maven/bin/mvnyjp b/tools/maven/bin/mvnyjp
--- a/tools/maven/bin/mvnyjp
+++ b/tools/maven/bin/mvnyjp
@@ -34,6 +34,14 @@
 #   MAVEN_SKIP_RC - flag to disable loading of mavenrc files
 # ----------------------------------------------------------------------------
 
+QUOTED_ARGS=""
+while [ "$1" != "" ] ; do
+
+  QUOTED_ARGS="$QUOTED_ARGS \"$1\""
+  shift
+
+done
+
 if [ -z "$MAVEN_SKIP_RC" ] ; then
 
   if [ -f /etc/mavenrc ] ; then
@@ -60,6 +68,10 @@ case "`uname`" in
            if [ -z "$JAVA_HOME" ] ; then
              JAVA_HOME=/System/Library/Frameworks/JavaVM.framework/Versions/${JAVA_VERSION}/Home
            fi
+           if [ -z "$YJP_HOME" ]; then
+             YJP_HOME=/Applications/YourKit.app
+           fi
+           YJPLIB=$YJP_HOME/bin/mac/libyjpagent.jnilib
            ;;
 esac
 
@@ -164,9 +176,18 @@ if $cygwin; then
     CLASSPATH=`cygpath --path --windows "$CLASSPATH"`
 fi
 
+if [ ! -f "$YJPLIB" ]; then
+  echo "Unable to autodetect the YJP library location. Please set YJPLIB variable"
+  exit 1
+fi
+
+MAVEN_OPTS="-agentpath:$YJPLIB=onexit=snapshot,onexit=memory,tracing,onlylocal $MAVEN_OPTS"
+
 exec "$JAVACMD" \
   $MAVEN_OPTS \
   -classpath "${M2_HOME}"/boot/plexus-classworlds-*.jar \
   "-Dclassworlds.conf=${M2_HOME}/bin/m2.conf" \
   "-Dmaven.home=${M2_HOME}"  \
-  ${CLASSWORLDS_LAUNCHER} "$@"
+  ${CLASSWORLDS_LAUNCHER} $QUOTED_ARGS
+
+
